version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file: .env
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${mongodb_user}
      - MONGO_INITDB_ROOT_PASSWORD=${mongodb_pass}
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_file: .env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${mongodb_express_user}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${mongodb_express_pass}
      - ME_CONFIG_MONGODB_SERVER=mongodb
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: .env
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${rabbitmq_user}
      RABBITMQ_DEFAULT_PASS: ${rabbitmq_pass}
    networks:
      - rabbitmq_network

volumes:
  data: { }
networks:
  default:
    name: mongodb_network
  rabbitmq_network:
    driver: bridge