version: "3.8"
services:
  analytics:
    image: "analytics"
    container_name: analytics
    build: analytics/
    ports:
      - "9001:9001"
    environment:
      SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE: admin
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: rootuser
      SPRING_DATA_MONGODB_PASSWORD: rootpass
      SPRING_DATA_MONGODB_DATABASE: analytics
      SPRING_RABBITMQ_ADDRESSES: rabbitmq:5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: root
    depends_on:
      - rabbitmq
      - mongodb
      - mongo-express
    networks:
      - shared-net
  device:
    container_name: device
    image: "device"
    build: device/
    ports:
      - "9000:9000"
    environment:
      SPRING_RABBITMQ_ADDRESSES: rabbitmq:5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: root
    depends_on:
      - rabbitmq
      - mongodb
      - mongo-express
    networks:
      - shared-net
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file: ../.env
    volumes:
      - data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    networks:
      - shared-net
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_file: ../.env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - shared-net
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: ../.env
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: root
    networks:
      - rabbitmq_network
      - shared-net
volumes:
  data: { }
networks:
  default:
    name: mongodb_network
  rabbitmq_network:
    driver: bridge
  shared-net:
    driver: bridge